"""phase 1: users, farmer_profiles, farms, crop_predictions

Revision ID: 8db31883d520
Revises: 
Create Date: 2026-09-13 09:40:05.087052
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '8db31883d520'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('farmer', 'expert', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('farmer_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('preferred_language', sa.Enum('mr', 'hi', 'en', name='language'), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('taluka', sa.String(length=80), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_profiles_district'), 'farmer_profiles', ['district'], unique=False)
    op.create_index(op.f('ix_farmer_profiles_user_id'), 'farmer_profiles', ['user_id'], unique=True)
    op.create_table('farms',
    sa.Column('farmer_profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('area_value', sa.Float(), nullable=False),
    sa.Column('area_unit', sa.Enum('acre', 'hectare', 'guntha', name='area_unit'), nullable=False),
    sa.Column('soil_type', sa.String(length=60), nullable=True),
    sa.Column('irrigation_source', sa.String(length=60), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('area_value > 0', name='ck_farms_area_positive'),
    sa.ForeignKeyConstraint(['farmer_profile_id'], ['farmer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_farmer_profile_id'), 'farms', ['farmer_profile_id'], unique=False)
    op.create_table('crop_predictions',
    sa.Column('farmer_profile_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('input_n', sa.Float(), nullable=False),
    sa.Column('input_p', sa.Float(), nullable=False),
    sa.Column('input_k', sa.Float(), nullable=False),
    sa.Column('input_temperature', sa.Float(), nullable=False),
    sa.Column('input_humidity', sa.Float(), nullable=False),
    sa.Column('input_ph', sa.Float(), nullable=False),
    sa.Column('input_rainfall', sa.Float(), nullable=False),
    sa.Column('recommended_crop', sa.String(length=60), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_crop_predictions_confidence_range'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farmer_profile_id'], ['farmer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_predictions_farm_id'), 'crop_predictions', ['farm_id'], unique=False)
    op.create_index('ix_crop_predictions_farmer_created', 'crop_predictions', ['farmer_profile_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_crop_predictions_farmer_profile_id'), 'crop_predictions', ['farmer_profile_id'], unique=False)
    op.create_index(op.f('ix_crop_predictions_model_version'), 'crop_predictions', ['model_version'], unique=False)
    op.create_index(op.f('ix_crop_predictions_recommended_crop'), 'crop_predictions', ['recommended_crop'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_predictions_recommended_crop'), table_name='crop_predictions')
    op.drop_index(op.f('ix_crop_predictions_model_version'), table_name='crop_predictions')
    op.drop_index(op.f('ix_crop_predictions_farmer_profile_id'), table_name='crop_predictions')
    op.drop_index('ix_crop_predictions_farmer_created', table_name='crop_predictions')
    op.drop_index(op.f('ix_crop_predictions_farm_id'), table_name='crop_predictions')
    op.drop_table('crop_predictions')
    op.drop_index(op.f('ix_farms_farmer_profile_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_farmer_profiles_user_id'), table_name='farmer_profiles')
    op.drop_index(op.f('ix_farmer_profiles_district'), table_name='farmer_profiles')
    op.drop_table('farmer_profiles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
